---
- name: Set up web server
  hosts: webservers
  become: yes
  gather_facts: no

  tasks:
    - name: Update apt cache
      shell: apt update -y

    - name: Install Nginx
      shell: apt install -y nginx

    - name: Ensure Nginx is enabled and started
      shell: systemctl enable --now nginx
